export enum Label {
    TRIP_CAPITALIZED = 'Trip',
    ADMIN_LOWER_CASE = 'admin',
    SUPERVISOR_LOWER_CASE = 'supervisor',
    DRIVER_LOWER_CASE = 'driver',
    DISPATCHER_LOWER_CASE = 'dispatcher',
    CORPORATE_LOWER_CASE = 'corporate',
    ADMIN_CAPITALIZED = 'Admin',
    SUPERVISOR_CAPITALIZED = 'Supervisor',
    DRIVER_CAPITALIZED = 'Driver',
    DISPATCHER_CAPITALIZED = 'Dispatcher',
    CORPORATE_CAPITALIZED = 'Corporate',
    CORPORATE_CLIENT_CAPITALIZED = 'Corporate Client',
    CUSTOMER_LOWER_CASE = 'customer',
    CUSTOMER_CAPITALIZED = 'Customer',
    FINANCE_CAPITALIZED = 'Finance',
    DATA_ANALYST_CAPITALIZED = 'Data Analyst',
    DISPATCHER_SUPERVISOR_LOWER_CASE = 'dispatcher supervisor',
    DISPATCHER_SUPERVISOR_CAPITALIZED = 'Dispatcher Supervisor',
    LEVEL = 'level',
    TOKEN = 'token',
    IS_LOGGED_IN = 'isLoggedIn',
    AUTHORIZATION = 'Authorization',
    TRUE = 'true'
}
